name: HOMMIE
description: A complete home services app solution.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core State Management
  provider: ^6.1.1

# State Management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  js: ^0.6.7

  # UI Components & Animations
  cupertino_icons: ^1.0.6
  animate_do: ^3.1.2
  timeline_tile: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1

  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0

  # Authentication & Social
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.4
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.2.0

  # Payment Integration
  flutter_stripe: ^10.1.0
  razorpay_flutter: ^1.3.5

  # Analytics & Monitoring
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_web_plugins:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
