// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiKMBKKOjzfcEyKYV8RVfu8Qx3ITR1jg',
    appId: '1:808565191689:web:55f1b50cf69bb0b7d334d8',
    messagingSenderId: '808565191689',
    projectId: 'hommie-ea778',
    authDomain: 'hommie-ea778.firebaseapp.com',
    storageBucket: 'hommie-ea778.firebasestorage.app',
    measurementId: 'G-MQLW2BQVMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XO0HAljgOD4Ky9HcViJmAlG4qtzrd_E',
    appId: '1:808565191689:android:da60beac731213c3d334d8',
    messagingSenderId: '808565191689',
    projectId: 'hommie-ea778',
    storageBucket: 'hommie-ea778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgBfYxTQgj1cW_xtn7vy1IKmpthqLFrJg',
    appId: '1:808565191689:ios:b55d78d67370df00d334d8',
    messagingSenderId: '808565191689',
    projectId: 'hommie-ea778',
    storageBucket: 'hommie-ea778.firebasestorage.app',
    iosBundleId: 'com.example.admin_panel_new',
  );
}
