name: Build and Release APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Generate app icon
      run: |
        mkdir -p assets/icon
        cp android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png assets/icon/icon.png
        flutter pub run flutter_launcher_icons
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: HOMMIE-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Build Debug APK
      run: flutter build apk --debug
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: HOMMIE-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
