name: Build APK with Java 17
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
    
    - name: Create dummy google-services.json
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "dummy",
            "project_id": "dummy-project"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:dummy:android:dummy",
                "android_client_info": {
                  "package_name": "com.Magistry.Hommie"
                }
              },
              "oauth_client": [],
              "api_key": [
                {
                  "current_key": "dummy-key"
                }
              ],
              "services": {
                "appinvite_service": {
                  "other_platform_oauth_client": []
                }
              }
            }
          ],
          "configuration_version": "1"
        }
        EOF
    
    - name: Debug Environment
      run: |
        echo "=== Java Version ==="
        java -version
        echo "=== Flutter Version ==="
        flutter --version
        echo "=== Flutter Doctor ==="
        flutter doctor -v
        echo "=== Android SDK ==="
        flutter doctor --android-licenses || true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Debug Gradle Configuration
      run: |
        cd android
        echo "=== Making gradlew executable ==="
        chmod +x gradlew
        echo "=== Gradle Wrapper Version ==="
        ./gradlew --version
        echo "=== Available Gradle Tasks ==="
        ./gradlew tasks --stacktrace
    
    - name: Build APK with detailed logs
      run: flutter build apk --debug --verbose
    
    - name: Fallback - Direct Gradle Build with stacktrace
      if: failure()
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace --info
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk/app-debug.apk
