name: admin_panel_new
description: "HOMMIE Admin Panel - Professional home service management platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Backend
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.4
  
  # State Management & Architecture
  provider: ^6.1.0
  
  # UI & Animations
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  
  # Charts & Analytics
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.58
  
  # Utilities & Tools
  intl: ^0.19.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  
  # Notifications & Messaging
  flutter_local_notifications: ^18.0.1
  
  # Data & Storage
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  
  # Network & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Utilities
  path: ^1.9.1
  crypto: ^3.0.5
  timezone: ^0.9.4
  
  # Development & Testing
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
